name: Matrix Configuration

on:
    push:
    workflow_dispatch:

jobs:
    docker-info:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, ubuntu-22.04, windows-latest]
                images: [hello-world, alpine]
                exclude:
                    - os: windows-latest
                      images: alpine
                include:
                    - os: ubuntu-latest
                      images: amd64/alpine
        steps:
            - name: Echo docker details
              run: docker info

            - name: Run Image on ${{ matrix.images }}
              run: docker run ${{ matrix.images }}